config/routes.rb
Rails.application.routes.draw do

get 'tasks', to: 'tasks#index'
post 'tasks', to: 'tasks#create', as: :task_create
get 'tasks/new', to: 'tasks#new', as: :new_task
get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
get 'tasks/:id', to: 'tasks#show', as: :task
patch 'tasks/:id', to: 'tasks#update', as: :task_update
delete 'task/:id', to: 'task#destroy', as: :task_delete

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to task_path(@task)
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form">
  <%= form_for(task) do |t| %>

      <%= t.label :title %>
      <input type="text" name="task[title]" id="task_title" class="form-control">

      <%= t.label :details %>
      <input type="text" name="task[details]" id="task_details" class="form-control">

      <%= t.label :completed %>
      <%= t.check_box :completed %>

      <%= t.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div>
  <h1>Edit <%= @task.title %></h1>
</div>

  <%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div>
  <h1>All tasks</h1>

  <% @tasks.each do |task| %>
  <h3> <%= link_to task.title, task_path(task) %> Completed: <%= task.completed %> </h3>
  <%= link_to "Delete task", task_delete_path(task), method: :delete %>
  <%= link_to 'Edit task', task_edit_path(task.id)  %>

  <% end %>
</div>

<div class="aa">
  <%= link_to "create new task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<div>
  <h1>Create a new Task</h1>
</div>
  <%= render'form', task: @task %>

app/views/tasks/show.html.erb
<div>
  <h1><%= @task.title %></h1>
  <%= link_to 'Edit task', task_edit_path(@task)  %>
  <%= link_to 'Task list', tasks_path  %>
</div>